version: "2"


services:

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    links:
      - "zookeeper:zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "10.200.100.171"
      KAFKA_ADVERTISED_PORT: "9092"

  rest-proxy:
    image: confluent/rest-proxy
    links:
      - "zookeeper:zookeeper"
      - "kafka:kafka"
      - "schema-registry:schema-registry"
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  schema-registry:
    image: confluent/schema-registry
    links:
      - "kafka:zookeeper"
      - "zookeeper:zookeeper"
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

##networks:
