version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZK_ID: "1"
  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: $DOCKER_MACHINE
      WAIT_FOR: dockerize -wait tcp://zookeeper:2181
  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      REST_PROXY_ZOOKEEPER_CONNECT: "zookeeper:2181"
      REST_PROXY_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      WAIT_FOR: dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -wait tcp://schema-registry:8082 -timeout 20s
  schema-registry:
    image: confluent/schema-registry
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      WAIT_FOR: dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9092 -timeout 20s
