zookeeper:
  image: confluent/zookeeper
  ports:
    - "2181"

schema-registry:
  image: confluent/schema-registry
  ports:
    - "8081:8081"
  links:
    - zookeeper
    - kafka

rest-proxy:
  image: confluent/rest-proxy
  ports:
    - "8082:8082"
  links:
    - zookeeper
    - kafka
    - schema-registry

kafka:
  image: confluent/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper
