#!/bin/bash

ZK_CFG_FILE="/etc/kafka/zookeeper.properties"

: ${zk_id:=1}
: ${zk_tickTime:=2000}
: ${zk_initLimit:=5}
: ${zk_syncLimit:=2}
: ${zk_dataDir:="/var/lib/zookeeper"}
: ${zk_clientPort:=2181}
: ${zk_maxClientCnxns:=0}

export zk_server_id
export zk_tickTime
export zk_initLimit
export zk_syncLimit
export zk_dataDir
export zk_clientPort
export zk_maxClientCnxns

# Download the config file, if given a URL
if [ ! -z "$zk_cfg_url" ]; then
  echo "[zk] Downloading zk config file from ${zk_cfg_url}"
  curl --location --silent --insecure --output ${zk_cfg_file} ${zk_cfg_url}
  if [ $? -ne 0 ]; then
    echo "[zk] Failed to download ${zk_cfg_url} exiting."
    exit 1
  fi
fi

# Process env variables
echo '# Generated by zk-docker.sh' > ${ZK_CFG_FILE}
for var in $(env | grep -v '^zk_cfg_' | grep '^zk_' | sort); do
  key=$(echo $var | sed -r 's/zk_(.*)=.*/\1/g')
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  if [[ $var =~ ^zk_server_[0-5]+= ]]; then
    server_id=`echo "$var" | sed -r "s/zk_server_(.*)=.*/\1/"`
    server_ip=`echo "$var" | sed 's/.*=//'`
    if [ "${server_id}" = "${zk_id}" ]; then
      echo "server.${server_id}=0.0.0.0:2888:3888" | tee -a $ZK_CFG_FILE
    else
      echo "server.${server_id}=${server_ip}:2888:3888" | tee -a $ZK_CFG_FILE
    fi
  else
    echo "${key}=${value}" >> ${ZK_CFG_FILE}
  fi
done

exec /usr/bin/zookeeper-server-start ${ZK_CFG_FILE}
