#!/bin/bash

: ${SCHEMA_REGISTRY_PORT:=8081}
: ${SCHEMA_REGISTRY_KAFKASTORE_TOPIC:=_schemas}
: ${SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL:=$ZOOKEEPER_PORT_2181_TCP_ADDR:$ZOOKEEPER_PORT_2181_TCP_PORT}
: ${SCHEMA_REGISTRY_DEBUG:=false}

export SCHEMA_REGISTRY_PORT
export SCHEMA_REGISTRY_KAFKASTORE_TOPIC
export SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
export SCHEMA_REGISTRY_DEBUG

echo '# Generated by schema_registry-docker.sh' > /etc/schema-registry/schema-registry.properties

for var in $(env | sort | grep '^SCHEMA_REGISTRY_'); do
    key=$(echo $var | sed -r 's/SCHEMA_REGISTRY_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
    value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
    echo "${key}=${value}" >> /etc/schema-registry/schema-registry.properties
done

exec /usr/bin/schema-registry-start /etc/schema-registry/schema-registry.properties
