#!/bin/bash

sr_cfg_file="/etc/schema-registry/schema-registry.properties"

: ${SR_PORT:=8081}
: ${SR_KAFKASTORE_TOPIC:=_schemas}
: ${SR_KAFKASTORE_CONNECTION_URL:=$ZOOKEEPER_PORT_2181_TCP_ADDR:$ZOOKEEPER_PORT_2181_TCP_PORT}
: ${SR_DEBUG:=false}

export SR_PORT
export SR_KAFKASTORE_TOPIC
export SR_KAFKASTORE_CONNECTION_URL
export SR_DEBUG

# Download the config file, if given a URL
if [ ! -z "$SR_CFG_URL" ]; THEN
  echo "[SR] Downloading SR config file from ${SR_CFG_URL}"
  curl --location --silent --insecure --output ${sr_cfg_file} ${SR_CFG_URL}
  if [ $? -ne 0 ]; then
    echo "[SR] Failed to download ${SR_CFG_URL} exiting."
    exit 1
  fi
fi

echo '# Generated by schema_registry-docker.sh' > ${sr_cfg_file}
for var in $(env | grep -v  '^SR_CFG_' | grep '^SR_' | sort); do
  key=$(echo $var | sed -r 's/SR_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${sr_cfg_file}
done

exec /usr/bin/schema-registry-start ${sr_cfg_file}
